name = "westerndiwanwesternnationalauthority"
main = "index.js"
compatibility_date = "2026-06-15"

[vars]
DATABASE_URL = "postgresql://neondb_owner:npg_YUnvxeQr6K8k@ep-sparkling-glitter-aprzy5tf-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
[build]
command = "npm install"
